# fly.toml app configuration file generated for fetcha-mysql-black-grass-6379 on 2024-12-08T20:13:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fetcha-mysql-black-grass-6379'
primary_region = 'sea'

[build]
  image = 'adeyomola/verba-mysql'

[processes]
  app = '--datadir /data/mysql --default-authentication-plugin caching_sha2_password --performance-schema=OFF --innodb-buffer-pool-size 64M'

[[mounts]]
  source = 'fetchadata'
  destination = '/data'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  processes = ['app']
